baseURL = "https://us.shoogle.net/nebraska"
languageCode = "en-US"
title = "Nebraska"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "nebraska"

[taxonomies]
  shop = "shops"

